site_name: Callbee Wiki-документация
site_url: http://callbee.io
# Структура навигации
nav:
  - О проекте: index.md
  - Возможности интеграции 1C: integration/settings_1c.md
  - Возможности интеграции amoCRM: integration/settings_amocrm.md
  - Возможности интеграции Bitrix24: integration/settings_bitrix24.md

  - Установка интеграции IP-ATC и CRM:
    - FreePBX и 1C: integration/freepbx_1c.md
    - FreePBX и amoCRM: integration/freepbx_amocrm.md
    - FreePBX и Bitrix24: integration/freepbx_bitrix24.md
    - Yeastar P-серия и amoCRM: integration/yeastar_p_amocrm.md
    - Yeastar S-серия и amoCRM: integration/yeastar_s_amocrm.md
    - Yeastar P-серия и Bitrix24: integration/yeastar_p_bitrix24.md
    - Yeastar S-серия и Bitrix24: integration/yeastar_s_bitrix24.md

  
theme:
  name: material
  language: ru
  theme:
  palette:
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
