site_name: Callbee Wiki
site_url: https://callbee.io
site_description: Callbee Wiki
copyright: Copyright &copy; 2021 <a href="https://callbee.io">Callbee</a>

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: ru
  theme:
  logo: img/logo.png
  favicon: img/favicon.png
  palette:
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search:
      lang:
        - ru
        - en
  - i18n:
      default_language: ru
      languages:
        ru: russian
        en: english
      material_alternate: false

extra:
  # generator: false
  alternate:
    - name: Russian
      link: ./ru/
      lang: ru
    - name: English
      link: ./en/
      lang: en
    
nav:
- index.ru.md
- amoCRM:
  - Asterisk + FreePBX: amoCRM/asterisk.ru.md
  - Yeastar PBX System: amoCRM/yeastar.ru.md
- Bitrix24:
  # - Asterisk + FreePBX: Bitrix24/asterisk.ru.md
  - Yeastar PBX System: Bitrix24/yeastar.ru.md
# - Moysklad:
  # - Asterisk + FreePBX: moysklad/asterisk.ru.md