site_name: сallbee wiki
site_url: https://callbee.io
site_description: callbee wiki
#copyright: Copyright &copy; 2025 <a href="https://callbee.io">сallbee</a>
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: ru
  theme:
  logo: static/logo.png
  favicon: static/favicon.png
nav:
  - О проекте: index.md
  - Обзор интеграций: products.md
  - Стоимость: price.md
  - Требования к системам:
    - Требования к CRM: requirements/crm.md
    - Требования к АТС: requirements/pbx.md
  - Установка:
    - Создание личного кабинета: install/cabinet.md
    - Подготовка CRM к интеграции: install/crm.md
    - Подготовка АТС к интеграции: install/pbx.md
    - Создание интеграции в личном кабинете: install/create.md
  - Настройка:
    - Настройка callbee в CRM: setup/crm.md
    - Настройка PBX для работы с callbee: setup/pbx.md
    - Обзор настроек в личном кабинете: setup/cabinet.md
  - Кастомизация: customization.md
  - FAQ: faq.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
  - glightbox
  - search