name: Deploy Retype to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: retypeapp/action-build@latest
        env:
          RETYPE_LICENSE_KEY: ${{ secrets.RETYPE_LICENSE_KEY }}

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
          branch: gh-pages
          cname: wiki.callbee.io
